homeInfoParams:
        Title: "Alexandre PHAM"

socialIcons:
    - name: GitHub
      url: "https://github.com/PhamAlexT/"
    - name: Linkedin
      url: "https://fr.linkedin.com/in/alexandre-pham-961a25220"

cover:
    responsiveImages: false
    linkFullImages: false


#ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowShareButtons: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true
